tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),  # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
]

# Ensure media files are served correctly during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.name
    

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=128,
        help_text="Please enter the category name."
    )
    views = forms.IntegerField(
        widget=forms.HiddenInput(),
        initial=0
    )
    likes = forms.IntegerField(
        widget=forms.HiddenInput(),
        initial=0
    )
    slug = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=128,
        help_text="Please enter the title of the page."
    )
    url = forms.URLField(
        max_length=200,
        help_text="Please enter the URL of the page."
    )
    views = forms.IntegerField(
        widget=forms.HiddenInput(),
        initial=0
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data
    
    class Meta:
        model = Page
        exclude = ('category',)  # Excluding the category field


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from rango.models import Category
from rango.models import Category, Page
from rango.forms import PageForm
from django.shortcuts import redirect
from .forms import CategoryForm
from rango.forms import UserForm, UserProfileForm
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def index(request):
    # Query the database for a list of categories ordered by likes (top 5).
    category_list = Category.objects.order_by('-likes')[:5]

    # Query the database for a list of pages ordered by views (top 5).
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_list,
        'pages': page_list  # Pass pages to the template
    }

    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    return render(request, 'rango/about.html')

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
        # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)  # Print errors to the console for debugging

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))
    else:
        print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):    
    registered = False  # Indicates if registration was successful

    if request.method == 'POST':
        # Retrieve form data from the POST request
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            # Save user form data to the database
            user = user_form.save(commit=False)
            user.set_password(user.password)  # Hash password
            user.save()

            # Create and save user profile
            profile = profile_form.save(commit=False)
            profile.user = user

            # If the user uploaded a picture, save it
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True  # Registration was successful
        else:
            # Print form errors for debugging
            print(user_form.errors, profile_form.errors)
    else:
        # Render empty forms for user registration
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the registration page with form data
    return render(
        request,
        'rango/register.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'registered': registered
        }
    )


def user_login(request):
    """Handles user authentication and login process."""

    if request.method == 'POST':
        # Get username and password from the form
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Authenticate user
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                # Log the user in and redirect to homepage
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Invalid login attempt
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    # If GET request, show login page
    return render(request, 'rango/login.html')


@login_required
def restricted(request):
    """Restricted page only visible to logged-in users."""
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <p>Here is the about page.</p>

    <p>This tutorial has been put together by <your-name>.</p>
    <p><a href="{% url 'rango:index' %}">Back to Index</a></p>
    
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>

    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}

        <!-- Render hidden fields -->
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <!-- Render visible fields with error messages -->
        {% for field in form.visible_fields %}
            <div>
                {{ field.label_tag }}
                {{ field }}
                <small>{{ field.help_text }}</small>
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li style="color: red;">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}

        <!-- Submit Button -->
        <input type="submit" name="submit" value="Create Category" />
    </form>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>

    <form id="page_form" method="post" action="{% url 'rango:add_page' category_name_slug=category.slug %}">
        {% csrf_token %}

        <!-- Render hidden fields -->
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <!-- Render visible fields with error messages -->
        {% for field in form.visible_fields %}
            <div>
                {{ field.label_tag }}  <!-- Adds a label for the field -->
                {{ field }}
                <small>{{ field.help_text }}</small>
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li style="color: red;">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}

        <!-- Submit Button -->
        <input type="submit" name="submit" value="Create Page">
    </form>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load rango_template_tags %}
{% load staticfiles %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rango - {% block title_block %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
    <div>
        {% block body_block %}

        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
        {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>

            {% endif %}
            <!-- Always show -->
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
        
    </div>
</body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul>
  {% if categories %} {% for c in categories %} {% if c == current_category %}
  <li>
    <strong>
      <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
    </strong>
  </li>
  {% else %}
  <li>
    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
  </li>
  {% endif %} {% endfor %} {% else %}
  <li><strong>There are no categories present.</strong></li>
  {% endif %}
</ul>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>

        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in this category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
        {% endif %}
    
    {% else %}
        <p>The specified category does not exist.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %} {% load static %} {% block title_block %}
Homepage {% endblock %} {% block body_block %}
<h1>Rango says...</h1>

<div>
  {% if user.is_authenticated %} howdy {{ user.username }}! {% else %} hey there
  partner! {% endif %} <br />
  <strong>
    {{ boldmessage }}</strong>
</div>

<!-- Most Liked Categories Section -->
<h2>Most Liked Categories</h2>
<div>
  {% if categories %}
  <ul>
    {% for category in categories %}
    <li>
      <a href="{% url 'rango:show_category' category.slug %}">
        {{ category.name }}
      </a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>There are no categories present.</strong>
  {% endif %}
</div>

<!-- Most Viewed Pages Section -->
<h2>Most Viewed Pages</h2>
<div>
  {% if pages %}
  <ul>
    {% for page in pages %}
    <li>
      <a href="{{ page.url }}">{{ page.title }}</a> ({{ page.views }} views)
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>There are no pages present.</strong>
  {% endif %}
</div>

<!-- Add Category Link -->
<div><a href="{% url 'rango:add_category' %}">Add a New Category</a><br /></div>

<!-- About Link and Image -->
<div>
  <a href="{% url 'rango:about' %}">About</a><br />
  <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
</div>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %} {% load staticfiles %} {% block title_block %}
Login {% endblock %} {% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
  {% csrf_token %} Username:
  <input type="text" name="username" value="" size="50" />
  <br />
  Password: <input type="password" name="password" value="" size="50" />
  <br />
  <input type="submit" value="submit" />
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>

    {% if registered %}
        <p>Rango says: <strong>Thank you for registering!</strong></p>
        <a href="{% url 'rango:index' %}">Return to the homepage</a>
    {% else %}
        <p>Rango says: <strong>register here!</strong></p>

        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Render hidden fields -->
            {% for hidden in user_form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <!-- Render visible fields with error messages -->
            {% for field in user_form.visible_fields %}
                <div>
                    {{ field.label_tag }}
                    {{ field }}
                    <small>{{ field.help_text }}</small>
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li style="color: red;">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            {% endfor %}

            {% for field in profile_form.visible_fields %}
                <div>
                    {{ field.label_tag }}
                    {{ field }}
                    <small>{{ field.help_text }}</small>
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li style="color: red;">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            {% endfor %}

            <!-- Submit Button -->
            <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>
    <p>This page is only accessible to registered users.</p>
{% endblock %}